/// FLUX-C v3 opcode definitions — 60 opcodes
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    // Stack (8)
    Push = 0x01,
    Pop = 0x02,
    Dup = 0x03,
    Swap = 0x04,
    Over = 0x05,
    Drop = 0x06,
    LoadConst = 0x07,
    Nop = 0x08,
    // Arithmetic (8)
    Add = 0x09,
    Sub = 0x0a,
    Mul = 0x0b,
    Div = 0x0c,
    Saturate = 0x0d,
    Min = 0x0e,
    Max = 0x0f,
    Abs = 0x10,
    // Register (4)
    LoadReg = 0x11,
    StoreReg = 0x12,
    LoadRegVec = 0x13,
    StoreRegVec = 0x14,
    // Constraint (10) — THE CORE
    RangeCheck = 0x15,
    BatchCheck = 0x16,
    AccumulateMask = 0x17,
    ClassifySeverity = 0x18,
    Prove = 0x19,
    QueryBackward = 0x1a,
    Simplify = 0x1b,
    Validate = 0x1c,
    HashCommit = 0x1d,
    Seal = 0x1e,
    // Vector/SIMD (6)
    VecLoad = 0x1f,
    VecStore = 0x20,
    VecRangeCheck = 0x21,
    VecMaskMerge = 0x22,
    VecReduce = 0x23,
    VecGather = 0x24,
    // Control (6)
    FwdJump = 0x25,
    CondJump = 0x26,
    CallBounded = 0x27,
    Ret = 0x28,
    Halt = 0x29,
    Checkpoint = 0x2a,
    // Effects (4)
    SetHandler = 0x2b,
    EmitEvent = 0x2c,
    Rollback = 0x2d,
    GetResult = 0x2e,
    // Parallel (4)
    ParDispatch = 0x2f,
    ParMerge = 0x30,
    ParBarrier = 0x31,
    ParReduce = 0x32,
    // Provenance (4)
    SnapRecord = 0x33,
    SnapQuery = 0x34,
    SnapHash = 0x35,
    SnapVerify = 0x36,
    // Streaming (4)
    StreamOpen = 0x37,
    StreamCheck = 0x38,
    StreamBatch = 0x39,
    StreamClose = 0x3a,
}

impl OpCode {
    pub fn from_u8(byte: u8) -> Option<Self> {
        match byte {
            0x01 => Some(Self::Push),
            0x02 => Some(Self::Pop),
            0x03 => Some(Self::Dup),
            0x04 => Some(Self::Swap),
            0x05 => Some(Self::Over),
            0x06 => Some(Self::Drop),
            0x07 => Some(Self::LoadConst),
            0x08 => Some(Self::Nop),
            0x09 => Some(Self::Add),
            0x0a => Some(Self::Sub),
            0x0b => Some(Self::Mul),
            0x0c => Some(Self::Div),
            0x0d => Some(Self::Saturate),
            0x0e => Some(Self::Min),
            0x0f => Some(Self::Max),
            0x10 => Some(Self::Abs),
            0x11 => Some(Self::LoadReg),
            0x12 => Some(Self::StoreReg),
            0x13 => Some(Self::LoadRegVec),
            0x14 => Some(Self::StoreRegVec),
            0x15 => Some(Self::RangeCheck),
            0x16 => Some(Self::BatchCheck),
            0x17 => Some(Self::AccumulateMask),
            0x18 => Some(Self::ClassifySeverity),
            0x19 => Some(Self::Prove),
            0x1a => Some(Self::QueryBackward),
            0x1b => Some(Self::Simplify),
            0x1c => Some(Self::Validate),
            0x1d => Some(Self::HashCommit),
            0x1e => Some(Self::Seal),
            0x1f => Some(Self::VecLoad),
            0x20 => Some(Self::VecStore),
            0x21 => Some(Self::VecRangeCheck),
            0x22 => Some(Self::VecMaskMerge),
            0x23 => Some(Self::VecReduce),
            0x24 => Some(Self::VecGather),
            0x25 => Some(Self::FwdJump),
            0x26 => Some(Self::CondJump),
            0x27 => Some(Self::CallBounded),
            0x28 => Some(Self::Ret),
            0x29 => Some(Self::Halt),
            0x2a => Some(Self::Checkpoint),
            0x2b => Some(Self::SetHandler),
            0x2c => Some(Self::EmitEvent),
            0x2d => Some(Self::Rollback),
            0x2e => Some(Self::GetResult),
            0x2f => Some(Self::ParDispatch),
            0x30 => Some(Self::ParMerge),
            0x31 => Some(Self::ParBarrier),
            0x32 => Some(Self::ParReduce),
            0x33 => Some(Self::SnapRecord),
            0x34 => Some(Self::SnapQuery),
            0x35 => Some(Self::SnapHash),
            0x36 => Some(Self::SnapVerify),
            0x37 => Some(Self::StreamOpen),
            0x38 => Some(Self::StreamCheck),
            0x39 => Some(Self::StreamBatch),
            0x3a => Some(Self::StreamClose),
            _ => None,
        }
    }

    /// Returns the number of immediate bytes consumed after this opcode
    pub fn imm_bytes(&self) -> usize {
        match self {
            Self::Push | Self::LoadConst => 4,
            Self::LoadReg | Self::StoreReg | Self::LoadRegVec | Self::StoreRegVec => 1,
            Self::FwdJump | Self::CondJump | Self::CallBounded => 2,
            _ => 0,
        }
    }
}
